apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: myecommerceacr21.azurecr.io/ecommerceapp:latest
        ports:
        - containerPort: 3000
